name: Hello World Workflow

on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a Hello World script
      run: echo "Hello, World! This is Anil"
