name: Hello World Workflow

runs-on: self-hosted

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a Hello World script
      run: echo "Hello, World! This is Anil Ramavath"
